# Generated by Django 4.2.16 on 2024-12-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dateShow',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='discription',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
