# Generated by Django 4.2.16 on 2024-12-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_dateshow_blog_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=100)),
                ('eventImage', models.ImageField(upload_to='events')),
                ('desc', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=200)),
                ('outfit', models.CharField(max_length=200)),
                ('imageNum', models.IntegerField(default=90)),
                ('graphy', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=1200)),
            ],
        ),
    ]
